# Generated by Django 3.1.7 on 2021-11-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_auto_20211126_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accept_terms',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
