# Generated by Django 3.1.7 on 2021-11-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096)),
                ('requirements', models.CharField(max_length=256)),
                ('level', models.CharField(max_length=256)),
            ],
        ),
    ]
