# Generated by Django 3.1.7 on 2021-11-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address_1', models.CharField(max_length=1024)),
                ('address_2', models.CharField(blank=True, max_length=1024, null=True)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('parking', models.CharField(blank=True, max_length=2048, null=True)),
                ('web_site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=1024),
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('backup_date', models.DateField()),
                ('capacity', models.IntegerField()),
                ('schedule_notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='enrollment.course')),
                ('lcoation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='enrollment.location')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='enrollment.semester')),
            ],
        ),
    ]
