# Generated by Django 3.1.7 on 2021-11-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_auto_20211127_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offering',
            old_name='lcoation',
            new_name='location',
        ),
    ]
