# Generated by Django 3.1.7 on 2021-11-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0012_auto_20211127_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='recital_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
