# Generated by Django 3.1.7 on 2021-11-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0013_semester_recital_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='hide',
            field=models.BooleanField(null=True),
        ),
    ]
