# Generated by Django 3.1.7 on 2021-11-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0016_auto_20211127_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='stored_subtitle',
            field=models.CharField(default='stored_subtitle', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offering',
            name='stored_title',
            field=models.CharField(default='stored_title', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='title', max_length=64),
            preserve_default=False,
        ),
    ]
