# Generated by Django 3.1.7 on 2021-11-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0017_auto_20211127_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='stored_subtitle',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='stored_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
