# Generated by Django 3.1.7 on 2021-11-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0018_auto_20211127_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='LineItem',
        ),
    ]
