# Generated by Django 3.1.7 on 2021-12-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0021_auto_20211127_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roster_notes',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
