# Generated by Django 3.1.7 on 2021-12-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0022_user_roster_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roster_notes',
            new_name='contact_sheet_notes',
        ),
    ]
