# Generated by Django 3.1.7 on 2021-12-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0026_giftcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard',
            old_name='expiration_month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='giftcard',
            old_name='expiration_year',
            new_name='year',
        ),
    ]
