# Generated by Django 3.1.7 on 2021-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0027_auto_20211207_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='hide',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='MISSING', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='MISSING', max_length=128),
            preserve_default=False,
        ),
    ]
