# Generated by Django 3.1.7 on 2021-12-10 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0030_auto_20211210_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offering',
            old_name='price',
            new_name='price_override',
        ),
    ]
