# Generated by Django 3.1.7 on 2021-12-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0032_auto_20211210_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
    ]
