# Generated by Django 3.1.7 on 2021-12-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0035_auto_20211212_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='recital_date',
            new_name='recital',
        ),
    ]
