# Generated by Django 3.1.7 on 2021-12-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0036_auto_20211212_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='You may use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a>to format this field.', max_length=4096),
        ),
    ]
